"""Add account_id to tasks table

Revision ID: 7cc4fcff7603
Revises: 7ae29958397f
Create Date: 2026-02-09 19:07:48.976406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc4fcff7603'
down_revision: Union[str, Sequence[str], None] = '7ae29958397f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('account_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_column('tasks', 'account_id')
    # ### end Alembic commands ###
